// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas.CRCL.CommandInstance {
    
    
    /// <remarks>
///
///        CRCLCommandInstanceType is derived from DataThingType.
///        An instance of CRCLCommandInstanceType has the following elements:
///          Name (inherited, optional)
///          CRCLCommand.
///
///        CRCLCommandInstanceType contains a single CRCL command.
///      
///</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CRCLCommandInstance")]
    public partial class CRCLCommandInstanceType : DataThingType {
        
        private CRCLCommandType cRCLCommandField;
        
        /// <remarks/>
        public CRCLCommandType CRCLCommand {
            get {
                return this.cRCLCommandField;
            }
            set {
                this.cRCLCommandField = value;
            }
        }
    }
    
    /// <remarks>
///
///        The abstract CRCLCommandType is derived from DataThingType.
///        An instance of CRCLCommandType has the following elements:
///          Name (inherited, optional)
///          CommandID.
///
///        CRCLCommandType is an abstract type from which all other
///        CRCL commands are derived.
///      
///</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CRCLCommandType : DataThingType {
        
        private string commandIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string CommandID {
            get {
                return this.commandIDField;
            }
            set {
                this.commandIDField = value;
            }
        }
    }
    
    /// <remarks>
///
///        An instance of DataThingType has the following elements:
///          Name (optional)
///          .
///
///        DataThingType is an abstract type from which more specific types
///        of data thing are derived. That includes all complex data
///        types such as VectorType, PoseType, etc.
///      
///</remarks>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRCLCommandInstanceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRCLCommandType))]
    public partial class DataThingType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
}
