// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas.CRCL.CommandInstance {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("CRCLCommandInstance", Namespace="", IsNullable=false)]
    public partial class CRCLCommandInstanceType : DataThingType {
        
        private CRCLCommandType cRCLCommandField;
        
        /// <remarks/>
        public CRCLCommandType CRCLCommand {
            get {
                return this.cRCLCommandField;
            }
            set {
                this.cRCLCommandField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiddleCommandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StopMotionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTorqueUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRotSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRotAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRobotParametersType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetMotionCoordinationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetLengthUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetIntermediatePoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetForceUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndPoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndEffectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndEffectorParametersType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetAngleUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RunProgramType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenToolChangerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveToType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveThroughToType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveScrewType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStatusType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DwellType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfigureJointReportsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CloseToolChangerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuateJointsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InitCanonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndCanonType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class CRCLCommandType : DataThingType {
        
        private string commandIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string CommandID {
            get {
                return this.commandIDField;
            }
            set {
                this.commandIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRCLCommandInstanceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ParameterSettingType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CRCLCommandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MiddleCommandType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StopMotionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTorqueUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRotSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRotAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRobotParametersType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetMotionCoordinationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetLengthUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetIntermediatePoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetForceUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndPoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndEffectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndEffectorParametersType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetAngleUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RunProgramType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenToolChangerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveToType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveThroughToType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveScrewType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStatusType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DwellType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfigureJointReportsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CloseToolChangerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuateJointsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InitCanonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EndCanonType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfigureJointReportType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JointDetailsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JointSpeedAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JointForceTorqueType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuateJointType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WrenchType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TwistType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotAccelRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotAccelAbsoluteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransAccelRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransAccelAbsoluteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotSpeedRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotSpeedAbsoluteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransSpeedRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransSpeedAbsoluteType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(VectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PoseType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PoseAndSetType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PointType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class DataThingType {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ParameterSettingType : DataThingType {
        
        private string parameterNameField;
        
        private string parameterValueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string ParameterName {
            get {
                return this.parameterNameField;
            }
            set {
                this.parameterNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
        public string ParameterValue {
            get {
                return this.parameterValueField;
            }
            set {
                this.parameterValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigureJointReportType : DataThingType {
        
        private string jointNumberField;
        
        private bool reportPositionField;
        
        private bool reportTorqueOrForceField;
        
        private bool reportVelocityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string JointNumber {
            get {
                return this.jointNumberField;
            }
            set {
                this.jointNumberField = value;
            }
        }
        
        /// <remarks/>
        public bool ReportPosition {
            get {
                return this.reportPositionField;
            }
            set {
                this.reportPositionField = value;
            }
        }
        
        /// <remarks/>
        public bool ReportTorqueOrForce {
            get {
                return this.reportTorqueOrForceField;
            }
            set {
                this.reportTorqueOrForceField = value;
            }
        }
        
        /// <remarks/>
        public bool ReportVelocity {
            get {
                return this.reportVelocityField;
            }
            set {
                this.reportVelocityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JointSpeedAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(JointForceTorqueType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class JointDetailsType : DataThingType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JointSpeedAccelType : JointDetailsType {
        
        private decimal jointSpeedField;
        
        private bool jointSpeedFieldSpecified;
        
        private decimal jointAccelField;
        
        private bool jointAccelFieldSpecified;
        
        /// <remarks/>
        public decimal JointSpeed {
            get {
                return this.jointSpeedField;
            }
            set {
                this.jointSpeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JointSpeedSpecified {
            get {
                return this.jointSpeedFieldSpecified;
            }
            set {
                this.jointSpeedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal JointAccel {
            get {
                return this.jointAccelField;
            }
            set {
                this.jointAccelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JointAccelSpecified {
            get {
                return this.jointAccelFieldSpecified;
            }
            set {
                this.jointAccelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class JointForceTorqueType : JointDetailsType {
        
        private decimal settingField;
        
        private bool settingFieldSpecified;
        
        private decimal changeRateField;
        
        private bool changeRateFieldSpecified;
        
        /// <remarks/>
        public decimal Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SettingSpecified {
            get {
                return this.settingFieldSpecified;
            }
            set {
                this.settingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ChangeRate {
            get {
                return this.changeRateField;
            }
            set {
                this.changeRateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChangeRateSpecified {
            get {
                return this.changeRateFieldSpecified;
            }
            set {
                this.changeRateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActuateJointType : DataThingType {
        
        private string jointNumberField;
        
        private decimal jointPositionField;
        
        private JointDetailsType jointDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string JointNumber {
            get {
                return this.jointNumberField;
            }
            set {
                this.jointNumberField = value;
            }
        }
        
        /// <remarks/>
        public decimal JointPosition {
            get {
                return this.jointPositionField;
            }
            set {
                this.jointPositionField = value;
            }
        }
        
        /// <remarks/>
        public JointDetailsType JointDetails {
            get {
                return this.jointDetailsField;
            }
            set {
                this.jointDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class WrenchType : DataThingType {
        
        private VectorType forceField;
        
        private VectorType momentField;
        
        /// <remarks/>
        public VectorType Force {
            get {
                return this.forceField;
            }
            set {
                this.forceField = value;
            }
        }
        
        /// <remarks/>
        public VectorType Moment {
            get {
                return this.momentField;
            }
            set {
                this.momentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VectorType : DataThingType {
        
        private decimal iField;
        
        private decimal jField;
        
        private decimal kField;
        
        /// <remarks/>
        public decimal I {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
            }
        }
        
        /// <remarks/>
        public decimal J {
            get {
                return this.jField;
            }
            set {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        public decimal K {
            get {
                return this.kField;
            }
            set {
                this.kField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TwistType : DataThingType {
        
        private VectorType linearVelocityField;
        
        private VectorType angularVelocityField;
        
        /// <remarks/>
        public VectorType LinearVelocity {
            get {
                return this.linearVelocityField;
            }
            set {
                this.linearVelocityField = value;
            }
        }
        
        /// <remarks/>
        public VectorType AngularVelocity {
            get {
                return this.angularVelocityField;
            }
            set {
                this.angularVelocityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PoseToleranceType : DataThingType {
        
        private decimal xPointToleranceField;
        
        private bool xPointToleranceFieldSpecified;
        
        private decimal yPointToleranceField;
        
        private bool yPointToleranceFieldSpecified;
        
        private decimal zPointToleranceField;
        
        private bool zPointToleranceFieldSpecified;
        
        private decimal xAxisToleranceField;
        
        private bool xAxisToleranceFieldSpecified;
        
        private decimal zAxisToleranceField;
        
        private bool zAxisToleranceFieldSpecified;
        
        /// <remarks/>
        public decimal XPointTolerance {
            get {
                return this.xPointToleranceField;
            }
            set {
                this.xPointToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XPointToleranceSpecified {
            get {
                return this.xPointToleranceFieldSpecified;
            }
            set {
                this.xPointToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal YPointTolerance {
            get {
                return this.yPointToleranceField;
            }
            set {
                this.yPointToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool YPointToleranceSpecified {
            get {
                return this.yPointToleranceFieldSpecified;
            }
            set {
                this.yPointToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ZPointTolerance {
            get {
                return this.zPointToleranceField;
            }
            set {
                this.zPointToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZPointToleranceSpecified {
            get {
                return this.zPointToleranceFieldSpecified;
            }
            set {
                this.zPointToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal XAxisTolerance {
            get {
                return this.xAxisToleranceField;
            }
            set {
                this.xAxisToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool XAxisToleranceSpecified {
            get {
                return this.xAxisToleranceFieldSpecified;
            }
            set {
                this.xAxisToleranceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal ZAxisTolerance {
            get {
                return this.zAxisToleranceField;
            }
            set {
                this.zAxisToleranceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ZAxisToleranceSpecified {
            get {
                return this.zAxisToleranceFieldSpecified;
            }
            set {
                this.zAxisToleranceFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotAccelRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotAccelAbsoluteType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class RotAccelType : DataThingType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RotAccelRelativeType : RotAccelType {
        
        private decimal fractionField;
        
        /// <remarks/>
        public decimal Fraction {
            get {
                return this.fractionField;
            }
            set {
                this.fractionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RotAccelAbsoluteType : RotAccelType {
        
        private decimal settingField;
        
        /// <remarks/>
        public decimal Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransAccelRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransAccelAbsoluteType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class TransAccelType : DataThingType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransAccelRelativeType : TransAccelType {
        
        private decimal fractionField;
        
        /// <remarks/>
        public decimal Fraction {
            get {
                return this.fractionField;
            }
            set {
                this.fractionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransAccelAbsoluteType : TransAccelType {
        
        private decimal settingField;
        
        /// <remarks/>
        public decimal Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotSpeedRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RotSpeedAbsoluteType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class RotSpeedType : DataThingType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RotSpeedRelativeType : RotSpeedType {
        
        private decimal fractionField;
        
        /// <remarks/>
        public decimal Fraction {
            get {
                return this.fractionField;
            }
            set {
                this.fractionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RotSpeedAbsoluteType : RotSpeedType {
        
        private decimal settingField;
        
        /// <remarks/>
        public decimal Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransSpeedRelativeType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransSpeedAbsoluteType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class TransSpeedType : DataThingType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransSpeedRelativeType : TransSpeedType {
        
        private decimal fractionField;
        
        /// <remarks/>
        public decimal Fraction {
            get {
                return this.fractionField;
            }
            set {
                this.fractionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransSpeedAbsoluteType : TransSpeedType {
        
        private decimal settingField;
        
        /// <remarks/>
        public decimal Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PoseAndSetType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PoseType : DataThingType {
        
        private PointType pointField;
        
        private VectorType xAxisField;
        
        private VectorType zAxisField;
        
        /// <remarks/>
        public PointType Point {
            get {
                return this.pointField;
            }
            set {
                this.pointField = value;
            }
        }
        
        /// <remarks/>
        public VectorType XAxis {
            get {
                return this.xAxisField;
            }
            set {
                this.xAxisField = value;
            }
        }
        
        /// <remarks/>
        public VectorType ZAxis {
            get {
                return this.zAxisField;
            }
            set {
                this.zAxisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PointType : DataThingType {
        
        private decimal xField;
        
        private decimal yField;
        
        private decimal zField;
        
        /// <remarks/>
        public decimal X {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
            }
        }
        
        /// <remarks/>
        public decimal Y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        public decimal Z {
            get {
                return this.zField;
            }
            set {
                this.zField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PoseAndSetType : PoseType {
        
        private bool coordinatedField;
        
        private TransSpeedType transSpeedField;
        
        private RotSpeedType rotSpeedField;
        
        private TransAccelType transAccelField;
        
        private RotAccelType rotAccelField;
        
        private PoseToleranceType toleranceField;
        
        /// <remarks/>
        public bool Coordinated {
            get {
                return this.coordinatedField;
            }
            set {
                this.coordinatedField = value;
            }
        }
        
        /// <remarks/>
        public TransSpeedType TransSpeed {
            get {
                return this.transSpeedField;
            }
            set {
                this.transSpeedField = value;
            }
        }
        
        /// <remarks/>
        public RotSpeedType RotSpeed {
            get {
                return this.rotSpeedField;
            }
            set {
                this.rotSpeedField = value;
            }
        }
        
        /// <remarks/>
        public TransAccelType TransAccel {
            get {
                return this.transAccelField;
            }
            set {
                this.transAccelField = value;
            }
        }
        
        /// <remarks/>
        public RotAccelType RotAccel {
            get {
                return this.rotAccelField;
            }
            set {
                this.rotAccelField = value;
            }
        }
        
        /// <remarks/>
        public PoseToleranceType Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StopMotionType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTransAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetTorqueUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRotSpeedType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRotAccelType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetRobotParametersType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetMotionCoordinationType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetLengthUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetIntermediatePoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetForceUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndPoseToleranceType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndEffectorType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetEndEffectorParametersType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SetAngleUnitsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RunProgramType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OpenToolChangerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveToType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveThroughToType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MoveScrewType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MessageType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetStatusType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DwellType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ConfigureJointReportsType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(CloseToolChangerType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ActuateJointsType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public abstract partial class MiddleCommandType : CRCLCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StopMotionType : MiddleCommandType {
        
        private StopConditionEnumType stopConditionField;
        
        /// <remarks/>
        public StopConditionEnumType StopCondition {
            get {
                return this.stopConditionField;
            }
            set {
                this.stopConditionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum StopConditionEnumType {
        
        /// <remarks/>
        Immediate,
        
        /// <remarks/>
        Fast,
        
        /// <remarks/>
        Normal,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTransSpeedType : MiddleCommandType {
        
        private TransSpeedType transSpeedField;
        
        /// <remarks/>
        public TransSpeedType TransSpeed {
            get {
                return this.transSpeedField;
            }
            set {
                this.transSpeedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTransAccelType : MiddleCommandType {
        
        private TransAccelType transAccelField;
        
        /// <remarks/>
        public TransAccelType TransAccel {
            get {
                return this.transAccelField;
            }
            set {
                this.transAccelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetTorqueUnitsType : MiddleCommandType {
        
        private TorqueUnitEnumType unitNameField;
        
        /// <remarks/>
        public TorqueUnitEnumType UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum TorqueUnitEnumType {
        
        /// <remarks/>
        newtonMeter,
        
        /// <remarks/>
        footPound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRotSpeedType : MiddleCommandType {
        
        private RotSpeedType rotSpeedField;
        
        /// <remarks/>
        public RotSpeedType RotSpeed {
            get {
                return this.rotSpeedField;
            }
            set {
                this.rotSpeedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRotAccelType : MiddleCommandType {
        
        private RotAccelType rotAccelField;
        
        /// <remarks/>
        public RotAccelType RotAccel {
            get {
                return this.rotAccelField;
            }
            set {
                this.rotAccelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetRobotParametersType : MiddleCommandType {
        
        private ParameterSettingType[] parameterSettingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ParameterSetting")]
        public ParameterSettingType[] ParameterSetting {
            get {
                return this.parameterSettingField;
            }
            set {
                this.parameterSettingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetMotionCoordinationType : MiddleCommandType {
        
        private bool coordinatedField;
        
        /// <remarks/>
        public bool Coordinated {
            get {
                return this.coordinatedField;
            }
            set {
                this.coordinatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetLengthUnitsType : MiddleCommandType {
        
        private LengthUnitEnumType unitNameField;
        
        /// <remarks/>
        public LengthUnitEnumType UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum LengthUnitEnumType {
        
        /// <remarks/>
        meter,
        
        /// <remarks/>
        millimeter,
        
        /// <remarks/>
        inch,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetIntermediatePoseToleranceType : MiddleCommandType {
        
        private PoseToleranceType toleranceField;
        
        /// <remarks/>
        public PoseToleranceType Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetForceUnitsType : MiddleCommandType {
        
        private ForceUnitEnumType unitNameField;
        
        /// <remarks/>
        public ForceUnitEnumType UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum ForceUnitEnumType {
        
        /// <remarks/>
        newton,
        
        /// <remarks/>
        pound,
        
        /// <remarks/>
        ounce,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetEndPoseToleranceType : MiddleCommandType {
        
        private PoseToleranceType toleranceField;
        
        /// <remarks/>
        public PoseToleranceType Tolerance {
            get {
                return this.toleranceField;
            }
            set {
                this.toleranceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetEndEffectorType : MiddleCommandType {
        
        private decimal settingField;
        
        /// <remarks/>
        public decimal Setting {
            get {
                return this.settingField;
            }
            set {
                this.settingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetEndEffectorParametersType : MiddleCommandType {
        
        private ParameterSettingType[] parameterSettingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ParameterSetting")]
        public ParameterSettingType[] ParameterSetting {
            get {
                return this.parameterSettingField;
            }
            set {
                this.parameterSettingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SetAngleUnitsType : MiddleCommandType {
        
        private AngleUnitEnumType unitNameField;
        
        /// <remarks/>
        public AngleUnitEnumType UnitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    public enum AngleUnitEnumType {
        
        /// <remarks/>
        degree,
        
        /// <remarks/>
        radian,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunProgramType : MiddleCommandType {
        
        private string programTextField;
        
        /// <remarks/>
        public string ProgramText {
            get {
                return this.programTextField;
            }
            set {
                this.programTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class OpenToolChangerType : MiddleCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveToType : MiddleCommandType {
        
        private bool moveStraightField;
        
        private PoseType endPositionField;
        
        /// <remarks/>
        public bool MoveStraight {
            get {
                return this.moveStraightField;
            }
            set {
                this.moveStraightField = value;
            }
        }
        
        /// <remarks/>
        public PoseType EndPosition {
            get {
                return this.endPositionField;
            }
            set {
                this.endPositionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveThroughToType : MiddleCommandType {
        
        private bool moveStraightField;
        
        private PoseType[] waypointField;
        
        private string numPositionsField;
        
        /// <remarks/>
        public bool MoveStraight {
            get {
                return this.moveStraightField;
            }
            set {
                this.moveStraightField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Waypoint")]
        public PoseType[] Waypoint {
            get {
                return this.waypointField;
            }
            set {
                this.waypointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string NumPositions {
            get {
                return this.numPositionsField;
            }
            set {
                this.numPositionsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MoveScrewType : MiddleCommandType {
        
        private PoseType startPositionField;
        
        private PointType axisPointField;
        
        private decimal axialDistanceFreeField;
        
        private bool axialDistanceFreeFieldSpecified;
        
        private decimal axialDistanceScrewField;
        
        private decimal turnField;
        
        /// <remarks/>
        public PoseType StartPosition {
            get {
                return this.startPositionField;
            }
            set {
                this.startPositionField = value;
            }
        }
        
        /// <remarks/>
        public PointType AxisPoint {
            get {
                return this.axisPointField;
            }
            set {
                this.axisPointField = value;
            }
        }
        
        /// <remarks/>
        public decimal AxialDistanceFree {
            get {
                return this.axialDistanceFreeField;
            }
            set {
                this.axialDistanceFreeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AxialDistanceFreeSpecified {
            get {
                return this.axialDistanceFreeFieldSpecified;
            }
            set {
                this.axialDistanceFreeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public decimal AxialDistanceScrew {
            get {
                return this.axialDistanceScrewField;
            }
            set {
                this.axialDistanceScrewField = value;
            }
        }
        
        /// <remarks/>
        public decimal Turn {
            get {
                return this.turnField;
            }
            set {
                this.turnField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MessageType : MiddleCommandType {
        
        private string messageField;
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatusType : MiddleCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DwellType : MiddleCommandType {
        
        private decimal dwellTimeField;
        
        /// <remarks/>
        public decimal DwellTime {
            get {
                return this.dwellTimeField;
            }
            set {
                this.dwellTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConfigureJointReportsType : MiddleCommandType {
        
        private bool resetAllField;
        
        private ConfigureJointReportType[] configureJointReportField;
        
        /// <remarks/>
        public bool ResetAll {
            get {
                return this.resetAllField;
            }
            set {
                this.resetAllField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ConfigureJointReport")]
        public ConfigureJointReportType[] ConfigureJointReport {
            get {
                return this.configureJointReportField;
            }
            set {
                this.configureJointReportField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CloseToolChangerType : MiddleCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ActuateJointsType : MiddleCommandType {
        
        private ActuateJointType[] actuateJointField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ActuateJoint")]
        public ActuateJointType[] ActuateJoint {
            get {
                return this.actuateJointField;
            }
            set {
                this.actuateJointField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitCanonType : CRCLCommandType {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndCanonType : CRCLCommandType {
    }
}
